### PR TITLE
Added handler for the nREPL 'info' message handler

### PR DESCRIPTION
**Pull request by setzer22**
This makes cider-doc and related functions work.

### CODE REVIEW

**Comment by setzer22** [comment]
Hi, I'm very glad to be able to contribute!

As I told you on gitter, here's the PR that adds support for cider-doc in the embedded nREPL server. I tried not to mess up with the indentation style, but I see there's still a couple of whitespace-related changes. Please let me know if that is a problem!

**Comment by nasser** [comment]
This looks great!

Can you add a commit that adds your name to [CONTRIBUTORS](https://github.com/arcadia-unity/Arcadia/blob/master/CONTRIBUTORS.md) and acknowledge in the commit message that you've read and agreed to our [Contributor's Licence Agreement](https://github.com/arcadia-unity/Arcadia/blob/master/CONTRIBUTOR-LICENSE-AGREEMENT.md)? Instructions and details are in the [README](https://github.com/arcadia-unity/Arcadia#contributing).

**Comment by setzer22** [comment]
@nasser  Done! 

I'll try to keep improving the nREPL support in my free time. Do you happen to know any documentation of the protocol API? So far I've been reverse engineering it by looking at the requests sent by cider but for anything more complicated than this it might be complicated.

**Comment by nasser** [comment]
> @nasser Done!

Thanks!

> I'll try to keep improving the nREPL support in my free time. Do you happen to know any documentation of the protocol API? So far I've been reverse engineering it by looking at the requests sent by cider but for anything more complicated than this it might be complicated.

The protocol is documented at [nrepl.org](https://nrepl.org/nrepl/0.6.0/design/overview.html) but I used a lot of packet sniffing against cider to ensure that things were working correctly as well.

**Pull request merged**
