### PR TITLE
catch messages up

### PR DESCRIPTION
**Pull request by pjago**
am I doing this right ?

### CODE REVIEW

**Comment by selfsame** [comment]
Hi @pjago! Can you add your name to the `contributors.md`?

Also, are these backwards compatible with pre-2018 unity versions?

**Comment by pjago** [comment]
Hey @selfsame! I've updated `contributors.md`. 
Now I am checking if my changes won't break any use of OnLevelWasLoaded in Unity 5.0. 
I imagine the new hooks won't break anything as long as they're not called.

**Comment by pjago** [comment]
Ow. I just saw in the wiki that Arcadia is developed and tested Unity against 2017.2.x.
I mean I can say it works in 2017.3.0f3. haha

**Comment by selfsame** [comment]
@pjago looks good! pinging @nasser

**Comment by nasser** [comment]
Looks great! Thanks!

**Pull request merged**
