### PR TITLE
fixes #194 by marking open scenes as dirty after every repl eval

### LINKED ISSUE #194: Adding/removing hooks doesn't mark the scene as dirty
When you add and remove hooks to a game object via the repl the scene which contains the game object is not marked as dirty. This means that Unity will not offer to Save the scene on Quit and File->Save Scenes does not persist the changes to the game object. Right clicking on the scene in the Hierarchy and explicitly saving it _does_ persist the changes to disk.

It seems like the correct behavior here is for modifying hooks on game objects dirties the scene in which they are contained.

### PR DESCRIPTION
**Pull request by selfsame**

### CODE REVIEW

**Comment by nasser** [comment]
Will this work in export? I wonder if the `Util` class will be exported given that its in the Editor folder.

**Comment by selfsame** [comment]
yes `Util` is export safe (https://github.com/arcadia-unity/Arcadia/pull/207/files#diff-9b860989ac88a29767749416402e375fR2)

**Comment by nasser** [comment]
I meant I wonder if its presence in the Editor folder will keep it from being compiled in export. I'd want to test that before merging. Otherwise, A+.

**Comment by selfsame** [comment]
Ah yes `Editor` directory is ignored for builds. I've moved it to `Helpers/Util.cs`

**Pull request merged**
